name: Build Flipper Companion App

on:
  push:
    branches: [ main ]
    paths:
      - 'flipper_app/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-fap:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install ufbt
      run: |
        pip3 install --upgrade ufbt
        ufbt update --channel=release

    - name: Build Flipper app
      run: |
        cd flipper_app
        ufbt

    - name: Create GitHub Release
      if: success()
      uses: softprops/action-gh-release@v1
      with:
        tag_name: flipper-v1.0.${{ github.run_number }}
        name: Flipper Companion v1.0.${{ github.run_number }}
        body: |
          ## Flipper Zero Companion App

          **Install to Flipper:** `/apps/Tools/pentest_companion.fap`

          ### Installation
          1. Download pentest_companion.fap
          2. Connect Flipper to computer
          3. Open qFlipper
          4. Copy FAP to `/apps/Tools/`
          5. Reboot Flipper

          ### Usage
          - Run app on Flipper: Apps → Tools → Pentest Companion
          - Connect Android app via USB
          - Send SubGHz/RFID commands from phone

          🤖 Auto-built by GitHub Actions
        files: flipper_app/dist/pentest_companion.fap
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
