name: Build and Release APK (Path Fixed)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # This step finds gradlew and makes it executable wherever it is
      - name: Grant permissions
        run: find . -name "gradlew" -exec chmod +x {} +

      # This builds the APK by finding the right directory automatically
      - name: Build with Gradle
        run: |
          GRADLE_PATH=$(find . -name "gradlew" | head -n 1)
          GRADLE_DIR=$(dirname "$GRADLE_PATH")
          cd "$GRADLE_DIR"
          ./gradlew assembleDebug

      - name: Prepare APK for Release
        run: |
          mkdir -p release-artifacts
          find . -name "*.apk" -exec cp {} release-artifacts/Build-Output.apk \;

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: Build ${{ github.run_number }}
          files: release-artifacts/Build-Output.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
